name: test
on:
  workflow_dispatch:
    inputs:
      what:
        description: 'clang-tidy action'
        default: latest
        required: false
        type: string
  push:
    branches:
      - create-circleci-config-forked
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.LIEF_EXTENDED_PRIVATE_CLONE }}
          GH_REPO: ${{ secrets.LIEF_EXTENDED_REPO }}
        run: |
          git clone https://${GH_TOKEN}@github.com/${GH_REPO} src
      - name: Docker run
        shell: bash
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
        run: |
          docker run --rm \
           -e S3_KEY=$S3_KEY \
           -e S3_SECRET=$S3_SECRET \
           -v $GITHUB_WORKSPACE/src/:/src \
           --workdir /home/extended \
           --entrypoint /usr/bin/python3 \
           ${REGISTRY}/extended /src/.ci/gha/bootstrap


